import { ConsultationRecord } from "./types";

export const sampleConsultation: ConsultationRecord = {
  consultation: {
    id: "sample-001",
    title: "서울 성동구 성수동 후보지 A",
    sampleData: true,
    customerName: "홍길동",
    contact: "010-0000-0000",
    startupBudget: 150000000,
    preferredArea: "서울 성동구",
    hasExperience: false,
    storeType: "제조형",
    memo: "샘플 데이터 - 실제 주소/상권으로 오해 금지",
  },
  candidateStore: {
    address: "샘플 데이터: 서울 성동구 성수동 후보지 A",
    deposit: 50000000,
    rent: 4500000,
    maintenanceFee: 500000,
    premium: 30000000,
    exclusiveArea: 66,
    floor: "1층",
    frontage: 6,
    entrancePosition: "정면",
    signExposure: "보통",
    parkingAvailable: false,
    previousBusiness: "카페",
    contractPeriod: "2년",
    businessRestriction: "제과제빵 가능 여부 확인 필요",
    restorationScope: "천장/벽체 일부 원상복구",
    specialTerms: "배기 및 전기 증설 관련 특약 필요",
  },
  facilityCheck: {
    electricCapacity: "20kW 추정",
    electricExpansionPossible: "불확실",
    plumbingPossible: "가능",
    exhaustPossible: "불확실",
    ceilingHeight: "2.8m",
    restroom: "공용",
    fireSafetyChecked: false,
    pillarLocation: "중앙 1개",
    ovenMovePossible: "불확실",
    mixerMovePossible: "가능",
    prooferPlacementPossible: "가능",
    coldStoragePlacementPossible: "불확실",
    showcasePlacementPossible: "가능",
    productionSpaceSecured: "불확실",
    salesSpaceSecured: "가능",
    drawingConfirmed: false,
  },
  breakEven: {
    expectedUnitPrice: 8500,
    expectedDailyVisitors: 90,
    expectedDailySales: 765000,
    expectedMonthlySales: 22950000,
    materialCostRate: 0.34,
    laborCost: 5000000,
    rent: 4500000,
    maintenanceFee: 500000,
    cardFeeRate: 0.03,
    deliveryFeeRate: 0.04,
    adCost: 700000,
    otherFixedCost: 1200000,
    premium: 30000000,
  },
  brandMarketing: {
    brandConcept: "성수동 직장인을 위한 따뜻한 데일리 베이커리",
    founderStory: "좋은 재료와 기본기 있는 빵으로 동네 단골을 만들고 싶다는 동기",
    targetCustomer: "직장인, 동네 단골",
    signatureMenu: "버터 소금빵, 사워도우 샌드위치",
    brandTone: "친근한, 감성적인",
    localKeywords: "성수동 베이커리, 성수동 소금빵, 성수 브런치",
    naverPlaceStrategy: "오픈 전 사진/메뉴 세팅, 주차/영업시간/대표메뉴 고정",
    blogContentIdeas: "시그니처 메뉴 제작 과정, 출근길 추천 세트, 주간 한정 메뉴",
    instagramContentIdeas: "오븐 굽는 영상, 당일 라인업 카드뉴스, 고객 후기 리그램",
    reviewEventIdea: "오픈 1개월 리뷰 작성 시 아메리카노 또는 미니빵 증정",
  },
  interiorSketch: {
    interiorTone: "우드&크림",
    operationType: "테이크아웃 중심",
    showcasePosition: "전면 노출",
    counterPosition: "쇼케이스 옆",
    kitchenPosition: "후면",
    hallUsage: "2~4석",
    customerFlow: "입구 → 쇼케이스 → 계산 → 픽업 → 퇴장",
    staffFlow: "제조 → 진열 → 포장 → 픽업",
    lowCostIdeas: "조명 교체, 메뉴보드 정리, 시그니처 진열존 구성",
    checkRequired: "급배수 위치, 배기 방향, 전기 콘센트, 장비 반입 동선",
  },
};
